name: "[CI] Push"

permissions:
  content: read
  packages: read
  actions: read

defaults:
  run:
    shell: pwsh

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  placeholder:
    runs-on: ubuntu-latest
    permissions:
      content: write
      pull_request: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: placeholder
        run: Write-Host "placeholder"
