name: CI Update Changelog on PR Merge

on:
  pull_request:
    types: [closed]

permissions:
    contents: write
    pull-requests: write

jobs:
  update-changelog:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.base.ref }}
          token: ${{ secrets.PAT_TOKEN }}

      - name: Check if description is empty
        if: ${{ github.event.pull_request.body == '' }}
        run: |
          echo "Pull request description is required to update the changelog."
          exit 1

      - name: Extract PR info
        id: pr
        run: |
          echo "username=${{ github.event.pull_request.user.login }}" >> $GITHUB_OUTPUT
          echo "title=${{ github.event.pull_request.title }}" >> $GITHUB_OUTPUT
          echo "number=${{ github.event.pull_request.number }}" >> $GITHUB_OUTPUT
          echo "description<<EOF" >> $GITHUB_OUTPUT
          echo "${{ github.event.pull_request.body }}" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
          # Get date in YYYY-MM-DD
          echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Update CHANGELOG.md
        run: |
          {
            echo "## ${{ steps.pr.outputs.username }} ${{ steps.pr.outputs.title }} (#${{ steps.pr.outputs.number }})"
            echo "**${{ steps.pr.outputs.date }}**"
            echo ""
            echo "${{ steps.pr.outputs.description }}"
            echo ""
          } | cat - CHANGELOG.md > temp && mv temp CHANGELOG.md

      - name: Commit changes
        run: |
          git config --local user.name "github-actions"
          git config --local user.email "github-actions@github.com"

          git add CHANGELOG.md
          git commit -m "Update changelog for PR #${{ steps.pr.outputs.number }}" || echo "No changes to commit"
          git push origin ${{ github.event.pull_request.base.ref }}